# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_myuser_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='company',
        ),
    ]
